spring.application.name=D-TECT
spring.config.import=optional:file:./D-TECT/secrets.properties

# 서버 포트
server.port=8081

server.forward-headers-strategy=framework

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://project-db-campus.smhrd.com:3307/campus_25SW_LI_p3_4?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=campus_25SW_LI_p3_4
spring.datasource.password=smhrd4
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

app.aes.secret=pathfinder

# 내부 서비스 주소
app.model.base-url=http://127.0.0.1:8001
app.model.predict-path=/predict
app.model.connect-timeout-ms=5000
app.model.read-timeout-ms=60000

app.bot.base-url=http://127.0.0.1:8002
app.bot.connect-timeout-ms=5000
app.bot.read-timeout-ms=120000

# 업로드/세션
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2050MB
app.analysis.session-ttl-minutes=30
file.upload-dir=/uploads

# 메일
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_SEC_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.test-connection=false

spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}  # ìì¼ë©´ ë¹ê°
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8081/login/oauth2/authorization/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# NCP Object Storage
app.storage.provider=ncp
app.storage.endpoint=https://kr.object.ncloudstorage.com
app.storage.region=kr-standard
app.storage.access-key=${NCS_ACCESS_KEY}
app.storage.secret-key=${NCS_SECRET_KEY}
app.storage.bucket=${NCS_BUCKET_NAME}
app.storage.public-base-url=https://kr.object.ncloudstorage.com/${NCS_BUCKET_NAME}

# PDF
app.pdf.webhook-url=http://n8nKHS.n8nKHS.com/webhook/5c2243e0-ba5e-4a72-bea2-7f30916c817d
app.pdf.callback-url-template=http://n8nkhs.n8nkhs.com/api/analysis/{analId}/pdf-callback
app.pdf.connect-timeout-ms=5000
app.pdf.read-timeout-ms=60000