spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 로그/메일 디버그
spring.mail.properties.mail.debug=true
logging.level.com.smhrd.dtect=DEBUG
logging.level.org.springframework.security=INFO

# 테스트용 PDF 웹훅
app.pdf.webhook-url=http://n8nKHS.n8nKHS.com/webhook-test/5c2243e0-ba5e-4a72-bea2-7f30916c817d
