server.address=127.0.0.1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.mail.properties.mail.debug=false
logging.level.com.smhrd.dtect=INFO
logging.level.org.springframework.security=INFO

# 운영용 PDF
# app.pdf.webhook-url=http://n8nKHS.n8nKHS.com/webhook/5c2243e0-ba5e-4a72-bea2-7f30916c817d
