spring.application.name=D-TECT
spring.config.import=optional:file:./D-TECT/secrets.properties

# properties key = value

server.port = 8081
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://project-db-campus.smhrd.com:3307/campus_25SW_LI_p3_4?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username = campus_25SW_LI_p3_4
spring.datasource.password = smhrd4

spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform = org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql = false
spring.jpa.properties.hibernate.format_sql = true

spring.servlet.multipart.enabled = true

spring.servlet.multipart.max-file-size = 10MB

spring.servlet.multipart.max-request-size = 20MB

file.upload-dir = /uploads

app.aes.secret=pathfinder

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_SEC_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.test-connection=false

# ===== Google =====
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/authorization/google
spring.security.oauth2.client.registration.google.client-name=Google


spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}  # ìì¼ë©´ ë¹ê°
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8081/login/oauth2/authorization/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
# server.forward-headers-strategy=native

# ë¡ê·¸ ë ë²¨(ìì)
logging.level.com.smhrd.dtect=DEBUG
logging.level.org.springframework.security=INFO

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=14

# ===== Model server (URL 비워둠 → 스텁 모드) =====
# 로컬용 url
# app.model.base-url=http://127.0.0.1:8001
# Docker용 url
app.model.base-url=http://model-server:8001
app.model.predict-path=/predict
app.model.connect-timeout-ms=5000
app.model.read-timeout-ms=60000
	
# 세션 보관
app.analysis.session-ttl-minutes=30

# ===== PDF webhook =====
# 테스트용 URL
# app.pdf.webhook-url=http://n8nKHS.n8nKHS.com/webhook-test/5c2243e0-ba5e-4a72-bea2-7f30916c817d

# 실 사용시 URL
# app.pdf.webhook-url=http://n8nKHS.n8nKHS.com/webhook/5c2243e0-ba5e-4a72-bea2-7f30916c817d

# n8n 컨테이너 이름과 내부 포트 사용
app.pdf.webhook-url=http://n8n_workspace-n8n-1/webhook/5c2243e0-ba5e-4a72-bea2-7f30916c817d


# (선택1) 템플릿으로 명시
# app.pdf.callback-url-template=http://192.168.219.45:8081/api/analysis/{analId}/pdf-callback

# 도커용 템플릿 URL
app.pdf.callback-url-template=http://dtect:8081/api/analysis/{analId}/pdf-callback


# (선택) 타임아웃
app.pdf.connect-timeout-ms=5000
app.pdf.read-timeout-ms=60000


# 외부 챗봇 서버
app.bot.base-url=http://127.0.0.1:8002
app.bot.connect-timeout-ms=5000
app.bot.read-timeout-ms=120000

# === 저장소 선택 ===
# app.storage.provider=local
# app.storage.local-dir=/home/git/uploads/reports

# === NCP 사용 시 ===
app.storage.provider=ncp
app.storage.endpoint=https://kr.object.ncloudstorage.com
app.storage.region=kr-standard
app.storage.access-key=${NCS_ACCESS_KEY}
app.storage.secret-key=${NCS_SECRET_KEY}
app.storage.bucket=${NCS_BUCKET_NAME}
app.storage.public-base-url=https://kr.object.ncloudstorage.com/${NCS_BUCKET_NAME}

# HikariCP 풀 관련 설정
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
# 30분
spring.datasource.hikari.max-lifetime=1800000      
# 10분
spring.datasource.hikari.idle-timeout=600000       
# 5초
spring.datasource.hikari.validation-timeout=5000   
