spring.config.import=optional:file:./D-TECT/secrets.properties

server.forward-headers-strategy=framework

app.model.base-url=http://modeling:8001
app.bot.base-url=http://chatbot:8002

# OAuth는 혹시모르니..
#spring.security.oauth2.client.registration.kakao.redirect-uri=https://d-tect.smhrd.com/login/oauth2/authorization/kakao
#spring.security.oauth2.client.registration.google.redirect-uri=https://d-tect.smhrd.com/login/oauth2/authorization/google
